<?php

declare(strict_types=1);

namespace Symfony\Component\DependencyInjection\Loader\Configurator;

use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;

return static function (DefinitionConfigurator $definition): void {
    $definition->rootNode()
        ->children()
            ->arrayNode('aeat_client')
                ->info('Settings to connect with AEAT API.')
                ->isRequired()
                ->children()
                    ->booleanNode('is_entity_seal_certificate')
                        ->info('Set to true only if your PFX certificate is an entity seal certificate ("certificado de sello de entidad") to make AEAT API calls through its dedicated endpoints.')
                        ->defaultValue(false)
                    ->end()
                    ->booleanNode('is_prod_environment')
                        ->info('Set to true in production environment to make AEAT API real calls, only when you are 100% sure that what are you doing is correct.')
                        ->defaultValue(false)
                    ->end()
                    ->booleanNode('is_verifactu_mode')
                        ->info('Set to false only if your SIF operates in "No Veri*Factu" mode (records are not remitted to the AEAT unless requested): the generated QR codes then point to the AEAT "ValidarQRNoVerifactu" endpoint and drop the "VERI*FACTU" legend, which is only lawful for Veri*Factu remissions.')
                        ->defaultValue(true)
                    ->end()
                    ->scalarNode('pfx_certificate_filepath')
                        ->info('Absolute path to the PFX (PKCS#12) certificate file, its existence & readability are asserted when the AEAT client is built.')
                        ->isRequired()
                    ->end()
                    ->scalarNode('pfx_certificate_password')->isRequired()->end()
                    ->arrayNode('representative')
                        ->info('Optional fiscal identifier of the representative ("Representante") who sends the invoices on behalf of the taxpayer, remove if not applicable.')
                        ->children()
                            ->scalarNode('name')->isRequired()->end()
                            ->scalarNode('nif')->isRequired()->end()
                        ->end()
                    ->end()
                    ->booleanNode('requirement_is_last_submission')
                        ->info('Set to true when there are no more records to submit after the current remission upon request ("FinRequerimiento"), only used together with requirement_reference.')
                        ->defaultValue(false)
                    ->end()
                    ->scalarNode('requirement_reference')
                        ->info('AEAT requirement reference ("RefRequerimiento"), mandatory only for non-voluntary remissions upon request by the AEAT ("remisión por requerimiento").')
                        ->defaultNull()
                    ->end()
                    ->scalarNode('voluntary_remission_end_date')
                        ->info('End date of the voluntary remission period ("FechaFinVeriFactu") in "YYYY-MM-DD" format, only set it when ending Veri*Factu voluntary remission.')
                        ->defaultNull()
                        ->validate()
                            ->ifTrue(static fn ($date): bool => null !== $date && false === \DateTimeImmutable::createFromFormat('Y-m-d', (string) $date))
                            ->thenInvalid('The voluntary_remission_end_date value must use the "YYYY-MM-DD" date format.')
                        ->end()
                    ->end()
                    ->booleanNode('voluntary_remission_is_affected_by_incident')
                        ->info('Set to true if the voluntary remission was at some point affected by a technical incident ("Incidencia"), only used together with voluntary_remission_end_date.')
                        ->defaultValue(false)
                    ->end()
                ->end()
            ->end()
            ->arrayNode('computer_system')
                ->info('Who acts as SIF (developer) provider.')
                ->isRequired()
                ->children()
                    ->scalarNode('vendor_name')->isRequired()->end()
                    ->scalarNode('vendor_nif')->isRequired()->end()
                    ->scalarNode('name')->isRequired()->end()
                    ->scalarNode('id')->isRequired()->end()
                    ->scalarNode('version')->isRequired()->end()
                    ->scalarNode('installation_number')->isRequired()->end()
                    ->booleanNode('only_supports_verifactu')->defaultValue(false)->end()
                    ->booleanNode('supports_multiple_taxpayers')->defaultValue(false)->end()
                    ->booleanNode('has_multiple_taxpayers')->defaultValue(false)->end()
                ->end()
            ->end()
            ->arrayNode('fiscal_identifier')
                ->info('Who acts as AEAT legal taxpayer.')
                ->isRequired()
                ->children()
                    ->scalarNode('name')->isRequired()->end()
                    ->scalarNode('nif')->isRequired()->end()
                ->end()
            ->end()
        ->end()
    ;
};
